const spectrums = {
    'covid_19': {
        id: 'covid_19',
        name: 'COVID-19',
        version: '1.0',
        description: "This is just a long list of COVID-19 beliefs that are either conspiratorial in themselves or are linked to claims of conspiratorial cover-ups. They come from no particular sources.",
        statements: [
            ['5g', "COVID-19 symptoms are caused by 5G towers rather than by any virus"],
            ['af', "COVID-19 is not threatening to African populations"],
            ['bi', "COVID-19 was created in a bioweapons research program"],
            ['ch', "COVID-19 cannot affect true Christians"],
            ['ci', "COVID-19 was part of a CIA program to weaken Chinese influence"],
            ['cm', "COVID-19 vaccines have been monopolised by wealthy nations to the detriment of poor nations"],
            ['cp', "COVID-19 is being exploited to maximise corporate profit"],
            ['cs', "COVID-19 is a cover for human organ trafficking networks"],
            ['cv', "COVID-19 is cover story for something else that's happening"],
            ['dg', "COVID-19 vaccines pose a greater threat to the average person than the virus does"],
            ['dn', "COVID-19 mRNA vaccines permanently alter human DNA"],
            ['dp', "COVID-19 is being exploited to increase political polarisation"],
            ['fd', "COVID-19 originated in a bioweapons lab in North America"],
            ['fl', "COVID-19 is no more dangerous than influenza"],
            ['fr', "COVID-19 is being exploited to limit the freedom of citizens in western nations"],
            ['fx', "COVID-19 is being exploited to make the public give up their freedoms"],
            ['gr', "COVID-19 conspiracies exist and are part of larger global conspiracies such as a 'New World Order' or 'Great Reset'"],
            ['gi', "COVID-19 vaccine company shareholders include United States politicians"],
            ['ht', "COVID-19 mRNA vaccine boosters cause a high rate of heart attacks in young people"],
            ['hx', "COVID-19 doesn't exist; it's 100% a hoax"],
            ['ic', "COVID-19 is an internationalist conspiracy to undermine national sovereignty"],
            ['im', "COVID-19 has been disproportionately spread by immigrant communities"],
            ['in', "COVID-19 mRNA vaccines cause infertility in women"],
            ['vi', "COVID-19 mRNA vaccines manufacturers have histories of legal settlements, medical fraud convictions, and unapproved clinical trials."],
            ['iv', "COVID-19 treatments like Ivermectin or hydroxychloroquine are being suppressed for non-medical reasons"],
            ['jw', "COVID-19 is a conspiracy by Jewish globalists"],
            ['lt', "COVID-19 variants have consistently been less dangerous than authorities have claimed"],
            ['mk', "COVID-19 masks are a health risk"],
            ['mm', "COVID-19 vaccines provide less resistance to the virus than authorities have claimed"],
            ['nb', "COVID-19 vaccines injections contain technological materials such as nanobots or microchips"],
            ['nt', "COVID-19 vaccines have not been properly tested"],
            ['of', "COVID-19 infections have been under-reported by Chinese officials"],
            ['ov', "COVID-19 hospitalisations and deaths have been over-reported by doctors"],
            ['ox', "COVID-19 hospitalisations and deaths are being covered up by doctors, media, and politicians in western nations"],
            ['pw', "COVID-19 emergency powers are an attempt to permanently take power over citizens"],
            ['rs', "COVID-19 threats were ignored by US President Trump for political reasons"],
            ['rx', "COVID-19 threats were exaggerated in order to undermine US President Trump"],
            ['se', "COVID-19 was deliberately created and spread to sell vaccines"],
            ['st', "COVID-19 vaccines are being used to carry out mass sterilisations of specific ethnic groups"],
            ['td', "COVID-19 conspiracy theories are being used to sow mistrust in democratic governments and public institutions"],
            ['te', "COVID-19 tests are far less reliable than authorities are saying"],
            ['tf', "COVID-19 policies have not adequately protected personal freedom"],
            ['ts', "COVID-19 policies have not adequately protected personal safety"],
            ['us', "COVID-19 was created by the United States government"],
            ['ur', "COVID-19 hospitalisations and deaths are under-reported by doctors"],
            ['va', "COVID-19 variants are being gradually released to prolong the pandemic"],
            ['vt', "COVID-19 can be prevented with vitamins, good health, and our bodies' natural defenses"],
            ['wv', "COVID-19 escaped from the Wuhan Institute of Virology in China"],
            ['zh', "COVID-19 was created by the Chinese government"],
        ],
    },
    'us_2010s': {
        id: 'us_2010s',
        name: 'US 2010s',
        version: '1.0',
        description: "This top-ten list of mostly-American conspiracy theories appears in Chapter 2 " + 
            "of 'Escaping the Rabbit Hole' (Mick West, 2018). An updated list would include news media, " +
            "electoral fraud, COVID-19, and QAnon.",
        statements: [
            ['bp', "pharmaceutical companies conspire to maximise profit by selling drugs that people do not actually need"],
            ['gw', "climate change is not caused by man-made carbon emissions, and there's some other motive for claiming this"],
            ['jf', "people in addition to Lee Harvey Oswald were involved in the assassination of John F. Kennedy"],
            ['wt', "the events of 9/11 were arranged by elements within the US government"],
            ['ct', "the trails left behind aircraft are part of a secret spraying program"],
            ['ff', "shootings like Sandy Hook and Las Vegas either never happened or were arranged by people in power"],
            ['ml', "the moon landings were faked in a movie studio"],
            ['uf', "the US government has contact with aliens or crashed alien aircraft and is keeping it secret"],
            ['fe', "the earth is flat, but governments, business, and scientists all pretend it is a globe"],
            ['ro', "the ruling classes are a race of shape-shifting trans-dimensional reptiles"],
        ],
    },
};
export default spectrums;
