const spectrums = {
    'covid_19': {
        id: 'covid_19',
        name: 'COVID-19',
        version: '1.0',
        description: "This is a long list of COVID-19 beliefs that are either conspiratorial in themselves or are linked to claims of conspiratorial cover-ups.",
        statements: [
            ['5g', "COVID-19 symptoms are actually caused by 5G towers"],
            ['a2', "COVID-19 is targetted at reducing African populations"],
            ['af', "COVID-19 is not threatening to African populations"],
            ['bi', "COVID-19 was engineered as a bioweapon"],
            ['cc', "COVID-19 is only dangerous in cold seasons or climates"],
            ['ch', "COVID-19 cannot affect true Christians"],
            ['ci', "COVID-19 is part of a CIA program to weaken Chinese influence"],
            ['cm', "COVID-19 vaccines have been monopolised by wealthy nations to the detriment of poor nations"],
            ['cp', "COVID-19 is being exploited to maximise corporate profit"],
            ['cs', "COVID-19 is a cover for human organ trafficking networks"],
            ['cv', "COVID-19 is cover story for something else that's happening"],
            ['dc', "COVID-19 hospitalisations and deaths are under-reported by doctors"],
            ['dg', "COVID-19 vaccines pose a greater threat than the disease"],
            ['dn', "COVID-19 mRNA vaccination is a giant medical experiment"],
            ['dn', "COVID-19 mRNA vaccines permanently alter human DNA"],
            ['dp', "COVID-19 is being exploited to increase political polarisation"],
            ['fd', "COVID-19 originated in a bioweapons lab in North America"],
            ['fl', "COVID-19 is no more dangerous than influenza"],
            ['fr', "COVID-19 is being exploited to limit the freedom of citizens"],
            ['fx', "COVID-19 is being exploited to make the public give up their freedoms"],
            ['gr', "COVID-19 conspiracies are part of larger global conspiracies such as a 'New World Order' or 'Great Reset'"],
            ['hi', "COVID-19 is best treated by letting a population gain herd immunity"],
            ['ht', "COVID-19 mRNA vaccines cause a high rate of heart attacks in young people"],
            ['hx', "COVID-19 doesn't exist; it's 100% a hoax"],
            ['ic', "COVID-19 is an internationalist conspiracy to undermine national sovereignty"],
            ['im', "COVID-19 has been disproportionately spread by immigrant communities"],
            ['in', "COVID-19 mRNA vaccines cause infertility in women"],
            ['iv', "COVID-19 treatments like Ivermection or hydroxychloroquine are being suppressed for non-medical reasons"],
            ['jw', "COVID-19 is a conspiracy by Jewish globalists"],
            ['lt', "COVID-19 is less dangerous than we have been told"],
            ['mk', "COVID-19 masks are a health risk"],
            ['mm', "COVID-19 vaccines confer insufficient immunity to the virus"],
            ['nb', "COVID-19 vaccines injections contain nanobots"],
            ['nm', "COVID-19 can be prevented with simple non-medical remedies"],
            ['nt', "COVID-19 vaccines have not been properly tested"],
            ['of', "COVID-19 infections were initially under-reported by Chinese officials"],
            ['ov', "COVID-19 hospitalisations and deaths are over-reported by doctors"],
            ['ox', "COVID-19 hospitalisations and deaths are being covered up by doctors, media, and politicians in western nations"],
            ['po', "COVID-19 is a globalist plot to reduce population"],
            ['pw', "COVID-19 emergency powers will never be rescinded"],
            ['rs', "COVID-19 threats were minimised by US President Trump for political reasons"],
            ['se', "COVID-19 was created and spread to sell vaccines"],
            ['st', "COVID-19 vaccines are being used to carry out mass sterilisations of specific ethnic groups"],
            ['td', "COVID-19 conspiracy theories are being used to sow mistrust in democratic governments and public institutions"],
            ['te', "COVID-19 tests are far less reliable than authorities are saying"],
            ['tf', "COVID-19 policies have not adequately protected personal freedom"],
            ['ts', "COVID-19 policies have not adequately protected personal safety"],
            ['ty', "COVID-19 is being exploited to create tyranny"],
            ['us', "COVID-19 was created by the United States government"],
            ['va', "COVID-19 variants are being gradually released to prolong the pandemic"],
            ['vt', "COVID-19 can be prevented with vitamins and good health"],
            ['wd', "COVID-19 is something all major world governments are conspiring over"],
            ['wv', "COVID-19 escaped from the Wuham Institute of Virology in China"],
            ['zh', "COVID-19 was created by the Chinese government"],
        ],
    },
    'us_2018': {
        id: 'us_2018',
        name: 'US 2018',
        version: '1.0',
        description: "This top-ten list of mostly-American conspiracy theories appears in Chapter 2 " + 
            "of 'Escaping the Rabbit Hole' (Mick West, 2018). An updated list would include news media, " +
            "electoral fraud, COVID-19, and QAnon.",
        statements: [
            ['bp', "pharmaceutical companies conspire to maximise profit by selling drugs that people do not actually need"],
            ['gw', "climate change is not caused by man-made carbon emissions, and there's some other motive for claiming this"],
            ['jf', "people in addition to Lee Harvey Oswald were involved in the assassination of John F. Kennedy"],
            ['wt', "the events of 9/11 were arranged by elements within the US government"],
            ['ct', "the trails left behind aircraft are part of a secret spraying program"],
            ['ff', "shootings like Sandy Hook and Las Vegas either never happened or were arranged by people in power"],
            ['ml', "the moon landings were faked in a movie studio"],
            ['uf', "the US government has contact with aliens or crashed alien aircraft and is keeping it secret"],
            ['fe', "the earth is flat, but governments, business, and scientists all pretend it is a globe"],
            ['ro', "the ruling classes are a race of shape-shifting trans-dimensional reptiles"],
        ],
    },
};
export default spectrums;
